Add "make install" step to Travis build.

diff --git a/other/travis/autotools-script b/other/travis/autotools-script
--- a/other/travis/autotools-script
+++ b/other/travis/autotools-script
@@ -1,20 +1,27 @@
 #!/bin/sh
 
-set -e -x
+set -e -u -x
+. other/travis/env-$ENV.sh
 
 # Build toxcore and run tests.
 ./autogen.sh
-./configure \
+RUN ./configure \
   --with-libsodium-libs=$CACHE_DIR/lib \
   --with-libsodium-headers=$CACHE_DIR/include \
   --enable-daemon \
   --enable-logging \
   --enable-ntox
 
-make -j `nproc`
+# We use make instead of RUN $MAKE here, because the autotools build will only
+# ever run natively on the Linux container, never on a Windows cross compilation
+# docker instance or an OSX machine.
+make -j`nproc`
+
 # This doesn't currently work on Travis, because the autotools build is broken.
 # It does not look up libsodium by pkg-config, so without the --with flags it
 # won't find it. We don't care that much about distcheck at this point, but we
 # do care whether it configures/builds at all, which is exercised by the make
 # call above. Tests are executed by the cmake build.
-make distcheck -j `nproc` || true
+echo "*** make distcheck currently fails; see https://github.com/TokTok/toxcore/blob/master/other/travis/autotools-script#L16 ***"
+make distcheck -j`nproc` \
+  || echo "*** make distcheck has failed as expected; don't be alarmed ***"
