Update and fix FreeBSD setup on Travis-CI
- Bump FreeBSD to 12.1.
- Simplify stage1 logic.
- Re-try downloading the image from a different mirror if one fails.
- Use the `expect` utility instead of dealing with screen's log file.
- Re-run failed toxcore test one more time and in sequence.

diff --git a/.travis/cmake-freebsd-stage1 b/.travis/cmake-freebsd-stage1
--- a/.travis/cmake-freebsd-stage1
+++ b/.travis/cmake-freebsd-stage1
@@ -1,5 +1,7 @@
 #!/bin/sh
 
+# Download and initial setup of the FreeBSD VM
+
 ACTION="$1"
 
 set -eux
@@ -7,8 +9,6 @@ set -eux
 . .travis/cmake-freebsd-env.sh
 
 travis_install() {
-  . .travis/cmake-freebsd-install.sh
-
   git tag -l --sort=version:refname > GIT_TAGS
 
   OLD_PWD="$PWD"
@@ -18,83 +18,55 @@ travis_install() {
 
   # === Get the VM image, set it up and cache ===
 
-  # Create image if it's not cached or if this build script has changed
-  sha256sum "$OLD_PWD/.travis/cmake-freebsd-env.sh"      > /tmp/sha
-  sha256sum "$OLD_PWD/.travis/cmake-freebsd-install.sh" >> /tmp/sha
-  sha256sum "$OLD_PWD/.travis/cmake-freebsd-stage1"     >> /tmp/sha
-  if [ ! -f "./$IMAGE_NAME.tgz" ] || [ ! -f ./cmake-freebsd-stage1-all.sha256 ] || [ "`cat cmake-freebsd-stage1-all.sha256`" != "`cat /tmp/sha`" ]; then
-
+  # Create image if it's not cached, or if this build script has changed, or a new toxcore tag was pushed
+  sha256sum "$OLD_PWD/.travis/cmake-freebsd-env.sh"         > /tmp/sha
+  sha256sum "$OLD_PWD/.travis/cmake-freebsd-stage1"        >> /tmp/sha
+  sha256sum "$OLD_PWD/.travis/cmake-freebsd-stage1.expect" >> /tmp/sha
+  if [ ! -f "./$IMAGE_NAME.tgz" ] || [ ! -f ./cmake-freebsd-stage1-all.sha256 ] || [ "$(cat cmake-freebsd-stage1-all.sha256)" != "$(cat /tmp/sha)" ] || ! diff -u ./GIT_TAGS "$OLD_PWD/GIT_TAGS"; then
     rm -rf ./*
 
-    # https://download.freebsd.org/ftp/releases/VM-IMAGES/11.2-RELEASE/amd64/Latest/
-    DL_SHA512="0c3c232c7023c5036daeb5fbf68c2ddecf9703c74e317afcf19da91e83d0afcc526785571e2868894ce15cdb56b74fafa1ce9fd216469db91e021ac2ef8911e5"
-    # Selecting random mirror from https://www.freebsd.org/doc/handbook/mirrors-ftp.html
-    # Note that not all mirrors listed on that page are working, so we have removed them
-    # I'm so sorry, there are no arrays in sh and we are not using bash...
-    DL_MIRROR_1=1
-    DL_MIRROR_2=4
-    # There are 2 mirrors
-    DL_MIRROR_RANDOM=`expr $(date +%s) % 2 + 1`
-    DL_URL="ftp://ftp$(eval echo \$DL_MIRROR_$DL_MIRROR_RANDOM).us.freebsd.org/pub/FreeBSD/releases/VM-IMAGES/${FREEBSD_VERSION}-RELEASE/amd64/Latest/${IMAGE_NAME}.xz"
+    while true; do
+      # Selecting random mirror from https://www.freebsd.org/doc/handbook/mirrors-ftp.html
+      # Note that not all mirrors listed on that page are working, so we have removed them
+      # There are no arrays in sh so we get a bit clever
+      DL_MIRROR_1=1
+      DL_MIRROR_2=2
+      DL_MIRROR_3=3
+      DL_MIRROR_4=4
+      DL_MIRROR_5=5
+      DL_MIRROR_6=6
+      DL_MIRROR_7=7
+      DL_MIRROR_8=10
+      DL_MIRROR_9=11
+      DL_MIRROR_10=13
+      DL_MIRROR_11=14
 
-    wget "$DL_URL"
+      # There are 11 mirrors
+      DL_MIRROR_RANDOM=`expr $(date +%s) % 11 + 1`
+      DL_URL="ftp://ftp$(eval echo \$DL_MIRROR_$DL_MIRROR_RANDOM).us.freebsd.org/pub/FreeBSD/releases/VM-IMAGES/${FREEBSD_VERSION}-RELEASE/amd64/Latest/${IMAGE_NAME}.xz"
 
-    if ! ( echo "$DL_SHA512  $IMAGE_NAME.xz" | sha512sum -c --status - ) ; then
-        echo "Error: sha512 of $IMAGE_NAME.xz doesn't match the known one"
-        exit 1
+      # Make sure there are no partial downloads from the previous loop iterations
+      rm -rf ./*
+
+      wget --tries 1 "$DL_URL" && break
+    done
+
+    if ! ( echo "$IMAGE_SHA512  $IMAGE_NAME.xz" | sha512sum -c --status - ) ; then
+      echo "Error: sha512 of $IMAGE_NAME.xz doesn't match the known one"
+      exit 1
     fi
 
     unxz "$IMAGE_NAME.xz"
 
-    # With this we don't have to guess how long a command will run for and sleeping
-    # for that amount of time, risking either under sleeping or over sleeping, instead
-    # we will sleep exactly until the command is finished by printing out a unique
-    # string after the command is executed and then checking if it was printed.
-    execute_shell_and_wait()
-    {
-      # $RANDOM is a bash built-in, so we try to avoid name collision here by using ugly RANDOM_STR name
-      RANDOM_STR=$(< /dev/urandom tr -dc _A-Za-z0-9 | head -c16)
-      send_keys "$1;echo $RANDOM_STR
+    sudo apt-get update
+    sudo apt-get install -y qemu screen expect
 
-"
-      # \[1B is a control escape sequence for a new line in the terminal.
-      # We want to wait for <new-line>$RANDOM_STR instead of just $RANDOM_STR because
-      # $RANDOM_STR we have inputted with send_keys above would appear in the screenlog.0
-      # file and we don't want to match our input, we want to match the echo's output.
-      # The .\? optionally matches any character. Sometimes it happens that there is some
-      # random character inserved between the new line control escape sequence and $RANDOM_STR.
-      wait_for "\[1B.\?$RANDOM_STR"
-    }
+    # The downloaded image has little free disk space
+    qemu-img resize -f raw "$IMAGE_NAME" +5G
+
+    NPROC=$NPROC SSH_PORT=$SSH_PORT IMAGE_NAME="$IMAGE_NAME" screen "$OLD_PWD/.travis/cmake-freebsd-stage1.expect"
 
     start_vm
-
-    # Login as root user
-    send_keys 'root
-
-'
-
-    # Wait for the prompt
-    wait_for "root@.*:~"
-
-    # Configure network, ssh and start changing password
-    execute_shell_and_wait 'echo "ifconfig_em0=DHCP"          >> /etc/rc.conf'
-    execute_shell_and_wait 'echo "Port 22"                    >> /etc/ssh/sshd_config'
-    execute_shell_and_wait 'echo "PermitRootLogin yes"        >> /etc/ssh/sshd_config'
-    execute_shell_and_wait 'echo "PasswordAuthentication yes" >> /etc/ssh/sshd_config'
-    execute_shell_and_wait 'echo "PermitEmptyPasswords yes"   >> /etc/ssh/sshd_config'
-    execute_shell_and_wait 'echo "sshd_enable=YES"            >> /etc/rc.conf'
-    send_keys 'sh /etc/rc.d/netif restart && sh /etc/rc.d/sshd start && passwd
-'
-
-    # Wait for the password prompt
-    wait_for "Changing local password for root"
-
-    # Reset password to empty for the passwordless ssh to work
-    send_keys '
-'
-    wait_for "New Password"
-    send_keys '
-'
 
     # Update system
     RUN env PAGER=cat env ASSUME_ALWAYS_YES=YES freebsd-update --not-running-from-cron fetch
@@ -117,7 +89,6 @@ travis_install() {
                                                     gmake \
                                                     cmake \
                                                     pkgconf \
-                                                    opencv \
                                                     portaudio \
                                                     libsndfile \
                                                     texinfo \
@@ -130,60 +101,11 @@ travis_install() {
     # Create cache
     tar -Sczvf "$IMAGE_NAME.tgz" "$IMAGE_NAME"
     rm "$IMAGE_NAME"
-    rm screenlog.0
 
     cp "$OLD_PWD/GIT_TAGS" .
-    sha256sum "$OLD_PWD/.travis/cmake-freebsd-env.sh"      > cmake-freebsd-stage1-all.sha256
-    sha256sum "$OLD_PWD/.travis/cmake-freebsd-install.sh" >> cmake-freebsd-stage1-all.sha256
-    sha256sum "$OLD_PWD/.travis/cmake-freebsd-stage1"     >> cmake-freebsd-stage1-all.sha256
-
-    ls -lh
-  fi
-
-  # === Update the image on new version (tag) of toxcore ===
-
-  if ! diff -u ./GIT_TAGS "$OLD_PWD/GIT_TAGS" ; then
-    # Extract the cached image
-    tar -Sxzvf "$IMAGE_NAME.tgz"
-
-    start_vm
-
-    # Log in.
-    # Although qemu prints "login:" and "Password:" lines, they are not written into the screen's log
-    # file for some reason (perhaps not enough text to flush the buffer to a file?), so we can't use
-    # wait_for on them, we just use sleep to add hopefully enough delay.
-    sleep 5
-    # "login:"
-    send_keys 'root
-
-'
-    sleep 5
-    # "Password:"
-    send_keys '
-
-'
-    # Wait for the prompt
-    wait_for "root@.* ~"
-
-    # Update system
-    RUN PAGER=cat ASSUME_ALWAYS_YES=YES freebsd-update --not-running-from-cron fetch
-    RUN PAGER=cat ASSUME_ALWAYS_YES=YES freebsd-update --not-running-from-cron install || true
-
-    # Update packages
-    RUN PAGER=cat ASSUME_ALWAYS_YES=YES pkg upgrade
-
-    # === Cache the updated VM image ===
-
-    stop_vm
-
-    # Create/Update cache
-    rm "$IMAGE_NAME.tgz"
-    tar -Sczvf "$IMAGE_NAME.tgz" "$IMAGE_NAME"
-    rm "$IMAGE_NAME"
-    rm screenlog.0
-
-    cp "$OLD_PWD/GIT_TAGS" .
-
+    sha256sum "$OLD_PWD/.travis/cmake-freebsd-env.sh"         > cmake-freebsd-stage1-all.sha256
+    sha256sum "$OLD_PWD/.travis/cmake-freebsd-stage1"        >> cmake-freebsd-stage1-all.sha256
+    sha256sum "$OLD_PWD/.travis/cmake-freebsd-stage1.expect" >> cmake-freebsd-stage1-all.sha256
     ls -lh
   fi
 
